# CREDITS ALT-LEDGER 2030 - Configuration File
# 
# This file contains the configuration for the standalone blockchain node
# Supports all three migration phases with customizable parameters

[node]
# Node identification
validator_id = "validator_1"
node_name = "credits-node-1"

# Network configuration
listen_port = 8080
rpc_port = 8081
enable_rpc = true

# Migration phase (1, 2, or 3)
phase = 3

# Data storage
data_dir = "./data"
log_level = "info"

[dag_engine]
# DAG engine configuration
storage_backend = "sled"  # Options: "sled", "rocksdb"
storage_path = "dag_data"
cache_size = 10000
max_vertices_per_shard = 1000000
min_vertices_per_shard = 100000

[consensus]
# Consensus configuration
voting_threshold = 0.67
max_validators = 100
round_timeout_seconds = 30
finality_depth = 10

[sharding]
# Sharding configuration
initial_shard_count = 4
rebalance_threshold = 0.8
max_shard_size = 1000000
min_shard_size = 100000

[networking]
# Network transport configuration
transport_protocol = "ctdp_v2"  # CTDP v2 transport
enable_quic = true
max_connections = 1000
connection_timeout_seconds = 30

[agent]
# Agent chain configuration
agent_name = "agent_1"
auto_commit = false
cns_enabled = true
agent_data_dir = "./agent_data"

[performance]
# Performance tuning
worker_threads = 4
max_memory_usage_mb = 1024
gc_interval_seconds = 60

[security]
# Security configuration
enable_tls = true
cert_file = "./certs/node.crt"
key_file = "./certs/node.key"
enable_rate_limiting = true
max_requests_per_second = 100

[logging]
# Logging configuration
log_file = "./logs/node.log"
max_log_size_mb = 100
log_rotation_count = 5
enable_metrics = true

[development]
# Development/testing options
enable_debug_api = false
simulate_network_delay = false
enable_profiling = false
test_mode = false